services:
  nextjs:
    image: ghcr.io/amarizzal/amarizzal_dev:latest
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - HOSTNAME=0.0.0.0
    env_file:
      - .env.production
    mem_limit: 100m
    networks:
      - npm_network

networks:
  npm_network:
    external: true
