services:
  nextjs:
    image: ghcr.io/amarizzal/amarizzal_dev:latest
    restart: unless-stopped
    expose:
      - "3000"
    env_file:
      - .env.production
    networks:
      - npm_network

networks:
  npm_network:
    external: true
